#pragma once

#define USB_POLLING_INTERVAL_MS 1

#define LED_DISABLE_WHEN_USB_SUSPENDED true
#define RGB_DISABLE_WHEN_USB_SUSPENDED true
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 17
#define RGBLIGHT_LAYER_BLINK
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
#define RGBLIGHT_STARTUP_ANIMATION

#define UNICODE_TYPE_DELAY 5
#define UNICODE_SELECTED_MODES UC_MAC, UC_LNX, UC_WINC

#define SPI_DEBUG_SCAN_RATE

#undef MANUFACTURER
#define MANUFACTURER Window of Fire
